name: iOS Release

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    name: Build and Release iOS App
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile

      - name: Build Next.js App
        run: pnpm build

      - name: Set Capacitor config for job4students.ro
        run: |
          echo '{
            "appId": "3234",
            "appName": "Job4Students",
            "webDir": "www",
            "server": {
              "url": "www.job4students.vercel.app",
              "cleartext": true
            }
          }' > capacitor.config.json

      - name: Install Capacitor CLI and iOS platform
        run: |
          pnpm add @capacitor/cli @capacitor/ios

      - name: Add iOS platform
        run: npx cap add ios || echo "iOS platform already added"

      - name: Sync Capacitor project
        run: npx cap sync ios

      - name: Install CocoaPods dependencies
        run: |
          cd ios/App
          pod install --repo-update
          cd ../../

      - name: Set up code signing
        env:
          APP_STORE_CONNECT_PRIVATE_KEY: ${{ secrets.APP_STORE_CONNECT_PRIVATE_KEY }}
          APP_STORE_CONNECT_KEY_ID: ${{ secrets.APP_STORE_CONNECT_KEY_ID }}
          APP_STORE_CONNECT_ISSUER_ID: ${{ secrets.APP_STORE_CONNECT_ISSUER_ID }}
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
        run: |
          # Import App Store Connect API key
          echo "$APP_STORE_CONNECT_PRIVATE_KEY" > AuthKey.p8
          # Install Fastlane
          gem install fastlane
          # Authenticate with App Store Connect
          fastlane run authenticate_app_store_connect_api_key \
            key_id:$APP_STORE_CONNECT_KEY_ID \
            issuer_id:$APP_STORE_CONNECT_ISSUER_ID \
            key_filepath:AuthKey.p8
          # Sync provisioning profiles using match
          fastlane match appstore --readonly

      - name: Build iOS Archive
        env:
          SCHEME: "MyApp"
          ARCHIVE_PATH: ${{ github.workspace }}/ios/build/MyApp.xcarchive
        run: |
          cd ios/App
          xcodebuild clean archive \
            -scheme "$SCHEME" \
            -sdk iphoneos \
            -archivePath "$ARCHIVE_PATH"

      - name: Export IPA
        env:
          EXPORT_PATH: ${{ github.workspace }}/ios/build/MyApp.ipa
        run: |
          cd ios/App
          xcodebuild -exportArchive \
            -archivePath "${{ env.ARCHIVE_PATH }}" \
            -exportOptionsPlist exportOptions.plist \
            -exportPath "${{ env.EXPORT_PATH }}"

      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v1.0.${{ github.run_number }}
          name: iOS Release v1.0.${{ github.run_number }}
          body: "Automated iOS release build for version 1.0.${{ github.run_number }}."
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload IPA to Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ env.EXPORT_PATH }}/MyApp.ipa
          asset_name: MyApp.ipa
          asset_content_type: application/octet-stream

      - name: Upload to TestFlight
        run: |
          fastlane deliver --ipa "${{ env.EXPORT_PATH }}/MyApp.ipa" --app_identifier "com.example.myapp"
        env:
          FASTLANE_APPLE_ID: ${{ secrets.APPLE_ID }}
          FASTLANE_PASSWORD: ${{ secrets.APPLE_PASSWORD }}
