name: Android Release

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    name: Build and Release Android APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile

      - name: Build Next.js App
        run: pnpm build

      - name: Set Capacitor config
        run: |
          cat <<EOF > capacitor.config.json
          {
            "appId": "com.jobstudents.app",
            "appName": "Job4Students",
            "webDir": "www",
            "server": {
              "url": "https://job4students.vercel.app",
              "cleartext": true
            }
          }
          EOF

      - name: Install Capacitor CLI and Android platform
        run: |
          pnpm add --save-dev @capacitor/cli
          pnpm add --save @capacitor/android

      - name: Add and sync Android platform
        run: |
          npx cap add android || echo "Android platform already added"
          npx cap sync android

      - name: Build Android APK
        run: |
          cd android
          ./gradlew assembleRelease

      - name: Sign APK
        env:
          KEYSTORE_FILE: ${{ secrets.ANDROID_KEYSTORE_BASE64 }}
          KEYSTORE_PASSWORD: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.ANDROID_KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.ANDROID_KEY_PASSWORD }}
        run: |
          echo "$KEYSTORE_FILE" | base64 --decode > android/app/keystore.jks
          jarsigner -verbose -sigalg SHA256withRSA -digestalg SHA-256 \
            -keystore android/app/keystore.jks -storepass "$KEYSTORE_PASSWORD" \
            -keypass "$KEY_PASSWORD" android/app/build/outputs/apk/release/app-release-unsigned.apk "$KEY_ALIAS"
          zipalign -v 4 android/app/build/outputs/apk/release/app-release-unsigned.apk android/app/build/outputs/apk/release/app-release.apk

      - name: Upload APK to GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v1.0.${{ github.run_number }}
          name: Android Release v1.0.${{ github.run_number }}
          body: "Automated Android release build for version 1.0.${{ github.run_number }}."
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload APK to Release
        uses: actions/upload-artifact@v3
        with:
          name: Job4Students.apk
          path: android/app/build/outputs/apk/release/app-release.apk

      - name: Upload to Google Play (Optional)
        run: |
          fastlane supply --track beta --json_key_data '${{ secrets.GOOGLE_PLAY_JSON_KEY }}' \
            --package_name "com.jobstudents.app" --apk "android/app/build/outputs/apk/release/app-release.apk"
        env:
          GOOGLE_PLAY_JSON_KEY: ${{ secrets.GOOGLE_PLAY_JSON_KEY }}
