name: iOS Release

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    name: Build and Release iOS App
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'  # Ensure Node.js version 20 is used

      - name: Install pnpm
        run: |
          npm install -g pnpm
          pnpm config set global-bin-dir $HOME/.pnpm-global/bin  # Set global bin directory
          echo "$HOME/.pnpm-global/bin" >> $GITHUB_PATH  # Add it to the PATH

      - name: Verify pnpm installation
        run: pnpm --version

      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile

      - name: Build Next.js App
        run: pnpm build

      - name: Set Capacitor appId and appName
        run: |
          echo '{
            "appId": "com.example.myapp",
            "appName": "MyApp",
            "webDir": "www"
          }' > capacitor.config.json

      - name: Install Capacitor CLI locally
        run: pnpm add @capacitor/cli  # Install Capacitor CLI locally

      - name: Verify Capacitor CLI installation
        run: |
          # Ensure @capacitor/cli is installed correctly
          ls node_modules/.bin/ | grep cap  # Check if 'cap' binary exists

      - name: Install iOS platform
        run: |
          npm install @capacitor/ios  # Install the iOS platform package

      - name: Add iOS platform
        run: |
          npx cap add ios || echo "iOS platform already added"  # Add iOS platform

      - name: Sync Capacitor project
        run: npx cap sync ios  # Synchronize the project

      - name: Install CocoaPods dependencies
        run: |
          cd ios
          pod install --repo-update
          cd ..

      - name: Open iOS project in Xcode
        run: |
          npx cap open ios  # Open the iOS project in Xcode

      - name: Build iOS Archive
        env:
          scheme: "MyApp"
          archive_path: ${{ github.workspace }}/ios/build/MyApp.xcarchive
        run: |
          cd ios/App
          xcodebuild clean archive \
            -scheme "$scheme" \
            -sdk iphoneos \
            -archivePath "$archive_path"

      - name: Export IPA
        env:
          export_path: ${{ github.workspace }}/ios/build/MyApp.ipa
        run: |
          cd ios/App
          xcodebuild -exportArchive \
            -archivePath "${{ env.archive_path }}" \
            -exportOptionsPlist exportOptions.plist \
            -exportPath "${{ env.export_path }}"

      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v1.0.${{ github.run_number }}
          name: iOS Release v1.0.${{ github.run_number }}
          body: "Automated iOS release build for version 1.0.${{ github.run_number }}."
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload IPA to Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ env.export_path }}/MyApp.ipa
          asset_name: MyApp.ipa
          asset_content_type: application/octet-stream

      - name: Upload to TestFlight
        run: |
          fastlane deliver --ipa "${{ env.export_path }}/MyApp.ipa" --app_identifier "com.example.myapp"
        env:
          FASTLANE_APPLE_ID: ${{ secrets.APPLE_ID }}
          FASTLANE_PASSWORD: ${{ secrets.APPLE_PASSWORD }}
